language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without benchmarks tools
script:
  - bundle exec rake
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.8
  - 2.6.7
  - 2.7.3
  - jruby-9.2.6.0
env:
  global:
    - COVERAGE=true
    - JRUBY_OPTS='--dev -J-Xmx1024M'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
